server:
  port: 8907
spring:
  application:
    name: cn-hw-demo
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8908/eureka/